# Generated by Django 4.1.2 on 2022-10-16 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdetails',
        ),
    ]
