# Generated by Django 4.1.2 on 2022-10-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0004_recruiter_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='recruiter_details',
        ),
    ]
