# Generated by Django 4.1.2 on 2022-10-20 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0007_recruiter_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter_details',
            name='gender',
        ),
    ]
