# Generated by Django 4.1.2 on 2022-10-23 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0008_remove_recruiter_details_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=250)),
                ('experience', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.recruiter_details')),
            ],
        ),
    ]
