# Generated by Django 4.1.2 on 2022-10-25 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0009_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='applied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(null=True, upload_to='')),
                ('applied_date', models.DateField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.userdetails')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_portal.jobs')),
            ],
        ),
    ]
