# Generated by Django 4.1.2 on 2022-10-25 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0010_applied'),
    ]

    operations = [
        migrations.DeleteModel(
            name='applied',
        ),
    ]
