# Generated by Django 4.1.2 on 2022-11-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0012_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
